version: '3.0'
services:
  proxy:
    build:
      context: ./proxy
    container_name: proxy
    ports:
    - "80:80"
    depends_on:
    - server
    networks:
      - back_net
  server:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: server
    ports: 
      - "3000:3000"
    restart: always
    networks:
      - back_net
networks:
  back_net:
    driver: bridge
