version: '3.0'
services:
  meetu:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: server
    ports: 
      - "3000:3000"
    restart: always
    networks:
      - back_net
networks:
  back_net:
    driver: bridge
