version: '3.0'
services:
  db:
    image: mysql:8.0
    restart: always
    container_name: db
    ports: 
      - "3306:3306"
    environment: 
      MYSQL_DB_HOST: db
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER_NAME: root
      MYSQL_DATABASE: test
      TZ: Asia/Seoul
    volumes:
      - ./data:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    networks:
      - back_net
    
  meetu:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: server
    ports: 
      - "3000:3000"
    restart: always
    depends_on:
      - db
    networks:
      - back_net
networks:
  back_net:
    driver: bridge
